"""empty message

Revision ID: 713952635bec
Revises: 695480964995
Create Date: 2023-12-19 22:23:57.638010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713952635bec'
down_revision = '695480964995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continent', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('continent')

    # ### end Alembic commands ###
